
import { NotebookText, LucideDotSquare, FlaskConical, Glasses, Zap, Snowflake, Columns2, Mountain } from 'lucide-react';
import { LuRainbow } from "react-icons/lu";

export const FONT_SIZES = [
  { label: 'Small', value: '14px' },
  { label: 'Medium', value: '16px' },
  { label: 'Large', value: '18px' },
  { label: 'XL', value: '20px' },
];

export const APP_THEMES = {
  // ── Curated ──
  default: {
    label: 'Default',
    icon: FlaskConical,
    group: 'special',
    bg: 'linear-gradient(270deg, #F7F7F8 0%, #F1F2F4 100%)',
    cardBg: 'bg-white/75 backdrop-blur',
    cardBorder: 'border-black/5',
    textPrimary: 'text-slate-800',
    textSecondary: 'text-slate-500',
    headerClass: '',
    bodyClass: '',
    iconStyle: null,
  },
  notes: {
    label: 'Notes',
    icon: NotebookText,
    group: 'special',
    bg: '#faf8f3',
    cardBg: 'bg-[#EDE5D388]',
    cardBorder: 'border-amber-200/80',
    textPrimary: 'text-stone-800',
    textSecondary: 'text-stone-500',
    headerClass: 'notes-theme',
    bodyClass: 'notes-theme',
    iconStyle: { background: 'linear-gradient(135deg, #DFD2B2 20%, #D1BF91 80%)' },
  },
  monochrome: {
    label: 'Monochrome',
    icon: LucideDotSquare,
    group: 'special',
    bg: '#f2f2f2',
    cardBg: 'bg-white',
    cardBorder: 'border-neutral-300',
    textPrimary: 'text-neutral-900',
    textSecondary: 'text-neutral-500',
    headerClass: 'mono-theme',
    bodyClass: 'mono-theme',
    iconStyle: { background: 'linear-gradient(135deg, #555 0%, #222 100%)' },
  },
  minimal: {
    label: 'Minimal',
    icon: Snowflake,
    group: 'special',
    bg: '#ffffff',
    cardBg: 'bg-gray-50',
    cardBorder: 'border-gray-200',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-500',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #9ca3af88 0%, #6b728099 100%)' },
  },
  modern: {
    label: 'Modern Dark',
    icon: Zap,
    group: 'special',
    bg: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    cardBg: 'bg-white/5 backdrop-blur-xl',
    cardBorder: 'border-white/10',
    textPrimary: 'text-white',
    textSecondary: 'text-blue-300',
    headerClass: 'dark-theme',
    bodyClass: 'dark-theme',
    isDark: true,
    iconStyle: { background: 'linear-gradient(135deg, #3b5bdb 0%, #1e40af 100%)' },
  },
  macosGlass: {
    label: 'Glass',
    icon: Glasses,
    group: 'special',
    bg: 'linear-gradient(180deg, #F8F8FA 0%, #EEF0F3 100%)',
    cardBg: 'bg-white/80 backdrop-blur-3xl',
    cardBorder: 'border-white/40',
    textPrimary: 'text-[#1D1D1F]',
    textSecondary: 'text-[#6E6E73]',
    headerClass: 'glass-theme',
    bodyClass: 'glass-theme',
    isGlass: true,
    iconTextColor: 'text-[#1D1D1F]',
    iconStyle: { background: 'rgba(255, 255, 255, 0.55)', backdropFilter: 'blur(16px)', border: '1px solid rgba(255, 255, 255, 0.65)', boxShadow: '0 8px 24px rgba(0,0,0,0.06)' },
  },
  macos26: {
    label: 'macOS Tahoe',
    icon: Mountain,
    group: 'special',
    // Rich "Lake Tahoe at dusk" — dark navy sky fading to deep azure water
    bg: 'linear-gradient(160deg, #061426 0%, #0d2d52 18%, #175490 36%, #1e6fa0 52%, #1860a0 68%, #104070 84%, #071e3d 100%)',
    cardBg: 'bg-white/10 backdrop-blur-3xl',
    cardBorder: 'border-white/20',
    textPrimary: 'text-white',
    textSecondary: 'text-blue-100/75',
    headerClass: 'macos26-theme',
    bodyClass: 'macos26-theme',
    isDark: true,
    isGlass: true,
    iconTextColor: 'text-white',
    iconStyle: {
      background: 'rgba(255, 255, 255, 0.14)',
      backdropFilter: 'blur(20px) saturate(200%)',
      border: '1px solid rgba(255, 255, 255, 0.35)',
      boxShadow: 'inset 0 1px 2px rgba(255, 255, 255, 0.55), 0 4px 20px rgba(0, 0, 0, 0.3)',
    },
  },
  pride: {
    label: 'LGBTQ+',
    icon: LuRainbow,
    group: 'special',
    bg: 'linear-gradient(45deg, #fce7f3 0%, #e0e7ff 50%, #d1fae5 100%)',
    cardBg: 'bg-white/80 backdrop-blur',
    cardBorder: 'border-slate-200/60',
    textPrimary: 'text-slate-800',
    textSecondary: 'text-slate-500',
    headerClass: 'pride-theme',
    bodyClass: 'pride-theme',
    iconTextColor: 'text-black',
    iconStyle: { background: 'linear-gradient(45deg, #ff0000, #ff8200, #ffef00, #41ff00, #0072ff, #5b00c1)' },
  },
  highContrast: {
    label: 'Black/White',
    icon: Columns2,
    group: 'special',
    bg: '#f1f1f1',
    cardBg: 'bg-white',
    cardBorder: 'border-black border-[3px]',
    textPrimary: 'text-black font-black',
    textSecondary: 'text-black font-bold',
    headerClass: 'hc-theme',
    bodyClass: 'hc-theme',
    iconStyle: { background: '#000000', border: '1px solid white' },
  },
  // ── Muted tones ─────────────────────────────────────────────────────────────
  steel: {
    label: 'Steel Blue',
    group: 'muted',
    bg: '#e8f0f3',
    cardBg: 'bg-[#f4f8fa]',
    cardBorder: 'border-[#aec8d2]',
    textPrimary: 'text-[#2c4a54]',
    textSecondary: 'text-[#5a8294]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #79a2b0 0%, #4e7f90 100%)' },
  },
  ash: {
    label: 'Ash Gray',
    group: 'muted',
    bg: '#e9ebea',
    cardBg: 'bg-[#f5f6f5]',
    cardBorder: 'border-[#b2beb5]',
    textPrimary: 'text-[#2e3330]',
    textSecondary: 'text-[#848884]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #848884 0%, #5a5f5c 100%)' },
  },
  charcoal: {
    label: 'Charcoal',
    group: 'muted',
    bg: '#d8dfe2',
    cardBg: 'bg-[#edf0f1]',
    cardBorder: 'border-[#9aacb4]',
    textPrimary: 'text-[#36454f]',
    textSecondary: 'text-[#5c7480]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #36454f 0%, #1e2d35 100%)' },
  },
  sage: {
    label: 'Sage',
    group: 'muted',
    bg: '#e4ebe9',
    cardBg: 'bg-[#f2f6f3]',
    cardBorder: 'border-[#a8bfac]',
    textPrimary: 'text-[#2d3d30]',
    textSecondary: 'text-[#5a7a5e]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #6b8f71 0%, #4a6b50 100%)' },
  },
  dusk: {
    label: 'Dusk',
    group: 'muted',
    bg: '#e5e3ee',
    cardBg: 'bg-[#f3f2f8]',
    cardBorder: 'border-[#b4afd0]',
    textPrimary: 'text-[#2e2b42]',
    textSecondary: 'text-[#6b6590]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #7b75a8 0%, #4e4878 100%)' },
  },
  sand: {
    label: 'Sand',
    group: 'muted',
    bg: '#ede8de',
    cardBg: 'bg-[#f7f4ee]',
    cardBorder: 'border-[#c9bfa8]',
    textPrimary: 'text-[#3d3628]',
    textSecondary: 'text-[#7a6e58]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #9c8c70 0%, #6e6050 100%)' },
  },
  dark: {
    label: 'Dark',
    group: 'muted',
    bg: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    cardBg: 'bg-slate-800/80 backdrop-blur',
    cardBorder: 'border-slate-700/60',
    textPrimary: 'text-slate-100',
    textSecondary: 'text-slate-400',
    headerClass: 'dark-theme',
    bodyClass: 'dark-theme',
    isDark: true,
    iconStyle: { background: 'linear-gradient(135deg, #475569 0%, #334155 100%)' },
  },
  girlyPink: {
    label: 'Girly Pink',
    group: 'muted',
    bg: 'linear-gradient(135deg, #fff1f5 10%, #FAD4F1 90%)',
    cardBg: 'bg-white/80',
    cardBorder: 'border-pink-200',
    textPrimary: 'text-pink-900',
    textSecondary: 'text-pink-500',
    headerClass: 'pink-theme',
    bodyClass: 'pink-theme',
    iconStyle: { background: 'linear-gradient(135deg, #ff85c0 20%, #f759fb 80%)' },
  },
};
